### ISSUE TITLE
QUESTION: For Loop Clarification

### ISSUE THREAD

**Issue by thejessicafelts** [Mitzi-S-Soto/piano#3]
Can you explain why you're using "i < 7" in your for loop "for (i=0; i<7; i++)"? If you're trying to target the key code, your range for keys is between 65 and 83, so 7 would be too low. If you're basing it on how many different keys you have assigned, it would still need to be "i <= 7" because you've assigned 7 keys. Let me know your process here (I could totally just be reading through your code wrong and missing something)...

**Comment by Mitzi-S-Soto** [comment]
i<7 because i starts at 0 so I only need 0-6 (making 7 notes)

**Comment by Mitzi-S-Soto** [comment]
it's working with an array and an array index starts with 0
